"""empty message

Revision ID: 3998dd206173
Revises: 
Create Date: 2018-12-04 18:25:32.228368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3998dd206173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionstable',
    sa.Column('q_id', sa.String(length=50), nullable=False),
    sa.Column('q_text', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('q_id')
    )
    op.create_table('responsestable',
    sa.Column('r_id', sa.String(length=50), nullable=False),
    sa.Column('href', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('r_id')
    )
    op.create_table('answerstable',
    sa.Column('a_id', sa.String(length=50), nullable=False),
    sa.Column('a_text', sa.String(length=2000), nullable=True),
    sa.Column('a_score', sa.Integer(), nullable=True),
    sa.Column('responses_id', sa.String(length=50), nullable=False),
    sa.Column('questions_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['questions_id'], ['questionstable.q_id'], ),
    sa.ForeignKeyConstraint(['responses_id'], ['responsestable.r_id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answerstable')
    op.drop_table('responsestable')
    op.drop_table('questionstable')
    # ### end Alembic commands ###
