"""empty message

Revision ID: 5790f8d1b552
Revises: 854cde45eb49
Create Date: 2018-12-18 12:21:46.897317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5790f8d1b552'
down_revision = '854cde45eb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offeredanswerstable',
    sa.Column('oa_id', sa.String(), nullable=False),
    sa.Column('oa_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('oa_id')
    )
    op.create_table('questionstable',
    sa.Column('q_id', sa.String(), nullable=False),
    sa.Column('q_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('q_id')
    )
    op.create_table('surveystable',
    sa.Column('s_id', sa.String(), nullable=False),
    sa.Column('s_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_table('surveysquestionstable',
    sa.Column('s_id', sa.String(), nullable=False),
    sa.Column('q_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['q_id'], ['questionstable.q_id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['surveystable.s_id'], ),
    sa.PrimaryKeyConstraint('s_id', 'q_id')
    )
    op.add_column('responsestable', sa.Column('r_status', sa.String(), nullable=True))
    op.drop_column('responsestable', 'r_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsestable', sa.Column('r_admin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('responsestable', 'r_status')
    op.drop_table('surveysquestionstable')
    op.drop_table('surveystable')
    op.drop_table('questionstable')
    op.drop_table('offeredanswerstable')
    # ### end Alembic commands ###
