"""empty message

Revision ID: 59ffe8184e35
Revises: 668f90be614d
Create Date: 2018-12-18 18:35:34.541474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ffe8184e35'
down_revision = '668f90be614d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offeredanswerstable', sa.Column('oa_id_2', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('offeredanswerstable', 'oa_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offeredanswerstable', sa.Column('oa_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('offeredanswerstable', 'oa_id_2')
    # ### end Alembic commands ###
