"""empty message

Revision ID: 668f90be614d
Revises: f69c2e3fe679
Create Date: 2018-12-18 18:34:49.699864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668f90be614d'
down_revision = 'f69c2e3fe679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsestable', sa.Column('r_test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responsestable', 'r_test')
    # ### end Alembic commands ###
