"""empty message

Revision ID: ccfd804832fd
Revises: 59ffe8184e35
Create Date: 2018-12-18 18:36:34.175190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfd804832fd'
down_revision = '59ffe8184e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offeredanswerstable', sa.Column('oa_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('offeredanswerstable', 'oa_id_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offeredanswerstable', sa.Column('oa_id_2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('offeredanswerstable', 'oa_id')
    # ### end Alembic commands ###
