"""empty message

Revision ID: f69c2e3fe679
Revises: e24bf24f17f9
Create Date: 2018-12-18 17:18:48.961532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69c2e3fe679'
down_revision = 'e24bf24f17f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveysquestionstable', sa.Column('q_id', sa.String(), nullable=False))
    op.add_column('surveysquestionstable', sa.Column('s_id', sa.String(), nullable=False))
    op.drop_constraint('surveysquestionstable_qa_id_fkey', 'surveysquestionstable', type_='foreignkey')
    op.drop_constraint('surveysquestionstable_sa_id_fkey', 'surveysquestionstable', type_='foreignkey')
    op.create_foreign_key(None, 'surveysquestionstable', 'surveystable', ['s_id'], ['s_id'])
    op.create_foreign_key(None, 'surveysquestionstable', 'questionstable', ['q_id'], ['q_id'])
    op.drop_column('surveysquestionstable', 'qa_id')
    op.drop_column('surveysquestionstable', 'sa_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveysquestionstable', sa.Column('sa_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('surveysquestionstable', sa.Column('qa_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'surveysquestionstable', type_='foreignkey')
    op.drop_constraint(None, 'surveysquestionstable', type_='foreignkey')
    op.create_foreign_key('surveysquestionstable_sa_id_fkey', 'surveysquestionstable', 'surveystable', ['sa_id'], ['s_id'])
    op.create_foreign_key('surveysquestionstable_qa_id_fkey', 'surveysquestionstable', 'questionstable', ['qa_id'], ['q_id'])
    op.drop_column('surveysquestionstable', 's_id')
    op.drop_column('surveysquestionstable', 'q_id')
    # ### end Alembic commands ###
