"""empty message

Revision ID: 12600b927559
Revises: 
Create Date: 2018-12-18 18:45:47.392372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12600b927559'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offeredanswerstable',
    sa.Column('oa_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oa_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('oa_id')
    )
    op.create_table('questionstable',
    sa.Column('q_id', sa.String(), nullable=False),
    sa.Column('q_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('q_id')
    )
    op.create_table('responsestable',
    sa.Column('r_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('r_public_id', sa.String(), nullable=True),
    sa.Column('r_status', sa.String(), nullable=True),
    sa.Column('r_test', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('r_id')
    )
    op.create_table('surveystable',
    sa.Column('s_id', sa.String(), nullable=False),
    sa.Column('s_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_table('surveysquestionstable',
    sa.Column('s_id', sa.String(), nullable=False),
    sa.Column('q_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['q_id'], ['questionstable.q_id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['surveystable.s_id'], ),
    sa.PrimaryKeyConstraint('s_id', 'q_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveysquestionstable')
    op.drop_table('surveystable')
    op.drop_table('responsestable')
    op.drop_table('questionstable')
    op.drop_table('offeredanswerstable')
    # ### end Alembic commands ###
