"""empty message

Revision ID: 854cde45eb49
Revises: bf35e36947ae
Create Date: 2018-12-14 21:14:17.859090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854cde45eb49'
down_revision = 'bf35e36947ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsestable', sa.Column('r_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responsestable', 'r_public_id')
    # ### end Alembic commands ###
