"""empty message

Revision ID: cc91c0859990
Revises: ccbaac80fd85
Create Date: 2018-12-18 22:02:30.643613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc91c0859990'
down_revision = 'ccbaac80fd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answerstable',
    sa.Column('a_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_score', sa.String(), nullable=True),
    sa.Column('s_id', sa.String(), nullable=False),
    sa.Column('q_id', sa.String(), nullable=False),
    sa.Column('oa_id', sa.Integer(), nullable=False),
    sa.Column('r_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['r_id'], ['responsestable.r_id'], ),
    sa.ForeignKeyConstraint(['s_id', 'q_id', 'oa_id'], ['surveysquestionsanswerstable.s_id', 'surveysquestionsanswerstable.q_id', 'surveysquestionsanswerstable.oa_id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answerstable')
    # ### end Alembic commands ###
