"""empty message

Revision ID: ccbaac80fd85
Revises: 12600b927559
Create Date: 2018-12-18 21:24:11.189881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbaac80fd85'
down_revision = '12600b927559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveysquestionsanswerstable',
    sa.Column('s_id', sa.String(), nullable=False),
    sa.Column('q_id', sa.String(), nullable=False),
    sa.Column('oa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oa_id'], ['offeredanswerstable.oa_id'], ),
    sa.ForeignKeyConstraint(['s_id', 'q_id'], ['surveysquestionstable.s_id', 'surveysquestionstable.q_id'], ),
    sa.PrimaryKeyConstraint('s_id', 'q_id', 'oa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveysquestionsanswerstable')
    # ### end Alembic commands ###
